[DRAFT] MODDATAIMP-860 - Create Service to Split Marc files - rev3
folio-org/mod-data-import pull request #264
Opened 2023-07-19 18:16 UTC by carolegodfrey

## Purpose
https://issues.folio.org/browse/MODDATAIMP-860 - Using a revised algorithm proposed by Taras for splitting files.

Issues with previous algorithm for splitting (not covering all cases for split)
https://github.com/folio-org/mod-data-import/pull/261
https://github.com/folio-org/mod-data-import/pull/262

## Approach
- Adds FileSplitWriter class which implements WriteStream Interface
- Adds Test Controller Method `http://localhost:8082/data-import/testFileSplit?key=20K.mrc` which accepts file on S3
- Streams file from S3
- Pipes input stream to FileSplitWriter which performs the splitting based on presence of RT byte in the file
- FileSplitWriter writers split chunk files locally and then uploads completed chunk files to S3

#### TODOS and Open Questions
- [ ] Check if AsyncInputStream is valid for convert of InputStream to ReadStream which can be pipedTo FileSplitWriter
(currently pulled code from https://gist.github.com/Stwissel/a7f8ce79785afd49eb2ced69b56335de)
- [ ] Clean up code 
- [ ] Add unit tests.
- [ ] Need to decide where temp files get written (data.import.storage.path setting is where current uploads get written) - S3 library uses system temp folder

## Learning

2023-08-01 14:45 UTC, evaluk commented
I updated to resolve all code smells.  Added some time stamp logging to track execution times of the split and upload. 

Stuff I did not do:  More thorough unit tests and any kind of wrapper over this file splitter to make it a service.  It will likely be called directly from the api start job api in this state.

2023-08-01 19:01 UTC, ncovercash requested changes
I haven't tested the code properly, but here are some initial comments/questions!

2023-08-03 18:48 UTC, ncovercash commented on src/main/java/org/folio/service/processing/split/FileSplitUtilities.java
> +@NoArgsConstructor(access = AccessLevel.PRIVATE)
Been getting this:
```
[WARNING] You aren't using a compiler supported by lombok, so lombok will not work and has been disabled.
Your processor is: org.aspectj.org.eclipse.jdt.internal.compiler.apt.dispatch.BatchProcessingEnvImpl
Lombok supports: OpenJDK javac, ECJ
        <unknown source file>:<no line information>
```

added a traditional constructor with exception

2023-08-04 03:52 UTC, ncovercash commented
making a clean PR.

2023-08-04 03:52 UTC, closed without merging